sudo: required

dist: trusty

# Travis is configured to run on pushed branches and pull requests so if we don't filter branches it runs twice when
# we push the PR branch in our repo
branches:
  only:
    - master
    #tag xx.yy-zz or xx.yy.zz-anythinglikeexperimental
    - /^\d+\.\d+(\.\d+)?(-\S*)?$/
    
services:
  - docker

language: python

install:
  - docker build -t container .

script:
  - docker run --name cont -d container
  - docker ps | grep -q cont
